name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag openhack-quarkus:$(date +%s)
      
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: user/openhack-quarkus:latest
        secrets: |
          GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}
